---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Enable Firewall
  ufw:
    state: enabled

- name: Upgrade packages
  apt:
    upgrade: dist
